#!/bin/bash

header()
{
	FILE=$1
	VAR=$2

	/usr/bin/xxd -i ${FILE} | sed 's/'${FILE}'/'${VAR}'/'
}

cd asm
make clean
PATH=../cc65-2.13.3/bin:$PATH make

(
header autoload autoloadcode 4
header inflate inflatecode 8
header fastload9600 fastload9600 4
header fastload8000 fastload8000 4
header fastloadcd fastloadcd 4
header diskload9600 diskload9600 4
header diskload8000 diskload8000 4
header diskload2 diskloadcode2 8
header diskload3 diskloadcode3 8
) > ../c2t.h.1

cd ..

cat <<EOF >c2t.h.2

//DOS 3.3
unsigned char dosboot1[] = {
EOF

cat mon/dos33.boot1.mon | \
	perl -p -e 's/ /,0x/g' | \
	perl -p -e 's/$/,/' | \
	perl -p -e 's/^....../\t/' >>c2t.h.2

cat <<EOF >>c2t.h.2
};

//DOS 3.3
unsigned char dosboot2[] = {
EOF

cat mon/dos33.boot2.mon | \
	perl -p -e 's/ /,0x/g' | \
	perl -p -e 's/$/,/' | \
	perl -p -e 's/^....../\t/' >>c2t.h.2

echo "};" >>c2t.h.2

cat c2t.h.[012] > c2t.h

rm -f c2t.h.[12]
